### ISSUE TITLE
Post-build TODO

### ISSUE THREAD

**Issue by jarelllama** [jarelllama/Scam-Blocklist#360]
- [x] Since the Google Search source only fetches results from the last 30 days now, document search terms with no results.
- [x] jeroengui.be phishing feed is way too large for the light version: use phishing and scam weekly for full, only scam weekly for light.
- [x] Revert jeroengui.be phishing domains added today from light to restore size.
- [x] Run today took 6 hours longer because the Dead Domains Linter API hung. To set job run time limite.
